# Generated by Django 4.2.1 on 2023-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
